from django.conf.urls.defaults import *

urlpatterns = patterns('proxynow5_proj.proxynow5.WebProxy_Filter.views',
                       (r'^wpfilter/$', 'wpfilter_page'),
                       
                       (r'^wpcat/$', 'wpcat_page'),
                       (r'^wpcat/save/$', 'wpcat_save'),
                       (r'^wpcat/delete/$', 'wpcat_delete'),
                       (r'^wpcat/list/$', 'wpcat_list'),
                       (r'^wpcat/list/panel/$', 'wpcat_list_panel'),
                       (r'^wpcat/list/panel/temp/$', 'wpcat_list_panel_temp'),
                       (r'^wpcat/list/select/$', 'wpcat_list_select'),
                       (r'^wpcat/list/select/temp/$', 'wpcat_list_select_temp'),
                       (r'^wpcat/save/temp/$', 'wpcat_save_temp'),
                       (r'^wpcat/url/save/$', 'wpcat_saveurl'),
                       (r'^wpcat/import/$', 'wpcat_import'),
                       (r'^wpcat/export/$', 'wpcat_export'),
                       
                       (r'^wpwhitelist/$', 'wpwhitelist_page'),
                       (r'^wpwhitelist/save/$', 'wpwhitelist_save'),
                       (r'^wpwhitelist/delete/$', 'wpwhitelist_delete'),
                       (r'^wpwhitelist/list/$', 'wpwhitelist_list'),
                       (r'^wpwhitelist/list/panel/$', 'wpwhitelist_list_panel'),
                       (r'^wpwhitelist/list/panel/temp/$', 'wpwhitelist_list_panel_temp'),
                       (r'^wpwhitelist/list/select/$', 'wpwhitelist_list_select'),
                       (r'^wpwhitelist/list/select/temp/$', 'wpwhitelist_list_select_temp'),
                       (r'^wpwhitelist/save/temp/$', 'wpwhitelist_save_temp'),
                       
                       (r'^wpblacklist/$', 'wpblacklist_page'),
                       (r'^wpblacklist/save/$', 'wpblacklist_save'),
                       (r'^wpblacklist/delete/$', 'wpblacklist_delete'),
                       (r'^wpblacklist/list/$', 'wpblacklist_list'),
                       (r'^wpblacklist/list/panel/$', 'wpblacklist_list_panel'),
                       (r'^wpblacklist/list/panel/temp/$', 'wpblacklist_list_panel_temp'),
                       (r'^wpblacklist/list/select/$', 'wpblacklist_list_select'),
                       (r'^wpblacklist/list/select/temp/$', 'wpblacklist_list_select_temp'),
                       (r'^wpblacklist/save/temp/$', 'wpblacklist_save_temp'),
                       
                       (r'^wpext/$', 'wpext_page'),
                       (r'^wpext/save/$', 'wpext_save'),
                       (r'^wpext/delete/$', 'wpext_delete'),
                       (r'^wpext/list/$', 'wpext_list'),
                       (r'^wpext/list/panel/$', 'wpext_list_panel'),
                       (r'^wpext/list/panel/temp/$', 'wpext_list_panel_temp'),
                       (r'^wpext/list/select/$', 'wpext_list_select'),
                       (r'^wpext/list/select/temp/$', 'wpext_list_select_temp'),
                       (r'^wpext/save/temp/$', 'wpext_save_temp'),
                       (r'^wpext/ext/save/$', 'wpext_saveext'),
                       
                       (r'^wpcontent/$', 'wpcontent_page'),
                       (r'^wpcontent/save/$', 'wpcontent_save'),
                       (r'^wpcontent/delete/$', 'wpcontent_delete'),
                       (r'^wpcontent/list/$', 'wpcontent_list'),
                       (r'^wpcontent/list/panel/$', 'wpcontent_list_panel'),
                       (r'^wpcontent/list/panel/temp/$', 'wpcontent_list_panel_temp'),
                       (r'^wpcontent/list/select/$', 'wpcontent_list_select'),
                       (r'^wpcontent/list/select/temp/$', 'wpcontent_list_select_temp'),
                       (r'^wpcontent/save/temp/$', 'wpcontent_save_temp'),
                       (r'^wpcontent/content/save/$', 'wpcontent_savecontent'),
                       (r'^wpcontent/export/$', 'wpcontent_export'),
                       
                       (r'^wpmime/$', 'wpmime_page'),
                       (r'^wpmime/save/$', 'wpmime_save'),
                       (r'^wpmime/delete/$', 'wpmime_delete'),
                       (r'^wpmime/list/$', 'wpmime_list'),
                       (r'^wpmime/list/panel/$', 'wpmime_list_panel'),
                       (r'^wpmime/list/panel/temp/$', 'wpmime_list_panel_temp'),
                       (r'^wpmime/list/select/$', 'wpmime_list_select'),
                       (r'^wpmime/list/select/temp/$', 'wpmime_list_select_temp'),
                       (r'^wpmime/save/temp/$', 'wpmime_save_temp'),
                       (r'^wpmime/mime/save/$', 'wpmime_savemime'),
)